import Navbar from "@/components/Navbar";
import "./global.css";

export const metadata = {
  title: "Music Play",
  description: "Generated by Rohit",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="bg-black max-[699px]:pt-28 ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
