import Navbar from "@/components/Navbar";
import "./global.css";

export const metadata = {
  title: "Music Play",
  description: "Generated by Rohit",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#414141" }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
